"comment" = "#777777"
"constant" = "red"
"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.hint" = { underline = { color = "cyan", style = "curl" } }
"diagnostic.info" = { underline = { color = "blue", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diff.delta" = "blue"
"diff.minus" = "red"
"diff.plus" = "green"
"error" = "red"
"function" = "yellow"
"function.macro" = "red"
"hint" = "cyan"
"info" = "blue"
"keyword" = "magenta"
"label" = "yellow"
"markup.bold" = { modifiers = ["bold"] }
"markup.heading" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link" = { fg = "blue" }
"markup.quote" = { fg = "#777777" }
"markup.raw" = { fg = "#777777" }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"namespace" = "blue"
"punctuation" = "#bbbbbb"
"string" = "green"
"tag" = "blue"
"tag.builtin" = "cyan"
"type" = "blue"
"ui.background" = { bg = "#000000" }
"ui.background.separator" = "#222222"
"ui.cursor" = { bg = "#aaaaaa" }
"ui.cursor.primary" = { modifiers = ["reversed"] }
"ui.cursorline" = { bg = "#111111" }
"ui.gutter.selected" = { bg = "#333333" }
"ui.help" = { bg = "#111111", fg = "#bbbbbb" }
"ui.highlight" = { bg = "#333333" }
"ui.highlight.frameline" = { bg = "#333333" }
"ui.linenr" = "#777777"
"ui.linenr.selected" = { bg = "#333333" }
"ui.menu" = { bg = "#111111" }
"ui.menu.scroll" = { bg = "#333333", fg = "blue" }
"ui.menu.selected" = "blue"
"ui.popup" = { bg = "#111111" }
"ui.popup.info" = { bg = "#1111111", fg = "#bbbbbb" }
"ui.selection" = { bg = "#333333" }
"ui.selection.primary" = { bg = "#05428f" }
"ui.statusline" = { bg = "#000000" }
"ui.statusline.active" = "blue"
"ui.statusline.insert" = "red"
"ui.statusline.normal" = "blue"
"ui.statusline.select" = "green"
"ui.statusline.separator" = "#777777"
"ui.text" = "#bbbbbb"
"ui.text.focus" = "blue"
"ui.virtual.indent-guide" = "#444444"
"ui.virtual.inlay-hint" = { fg = "#777777", modifiers = ["italic"] }
"ui.virtual.whitespace" = "#444444"
"ui.virtual.wrap" = "#777777"
"ui.window" = "#222222"
"variable" = "cyan"
"variable.builtin" = "magenta"
"warning" = "yellow"
