[colors.bright]
black = "0x444444"
red = "0xff443a"
green = "0x30d158"
yellow = "0xffd60a"
blue = "0x0a84ff"
magenta = "0xbf5af2"
cyan = "0x64d3ff"
white = "0xdddddd"

[colors.normal]
black = "0x000000"
red = "0xff443a"
green = "0x30d158"
yellow = "0xffd60a"
blue = "0x0a84ff"
magenta = "0xbf5af2"
cyan = "0x64d3ff"
white = "0xffffff"

[colors.primary]
background = "0x000000"
foreground = "0xdddddd"

[font]
size = 16.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[window]
decorations = "None"
option_as_alt = "Both"
startup_mode = "Maximized"

[window.padding]
x = 2
y = 2
