[colors.bright]
black = "0x444444"
blue = "0x0a84ff"
cyan = "0x64d3ff"
green = "0x30d158"
magenta = "0xbf5af2"
red = "0xff443a"
white = "0xdddddd"
yellow = "0xffd60a"

[colors.normal]
black = "0x000000"
blue = "0x0a84ff"
cyan = "0x64d3ff"
green = "0x30d158"
magenta = "0xbf5af2"
red = "0xff443a"
white = "0xffffff"
yellow = "0xffd60a"

[colors.primary]
background = "0x000000"
foreground = "0xdddddd"

[font]
size = 16.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[font.offset]
x = 0
y = 2

[[hints.enabled]]
command = "open"
hyperlinks = true

[window]
decorations = "None"
option_as_alt = "Both"
startup_mode = "Maximized"

[window.padding]
x = 8
y = 8
